name: CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=16384"
      FULL_ACCESS: ${{ secrets.FULL_ACCESS }}
      GIT_PR_REF: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn
      - run: ./build-script/vercel.sh