name: CI

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DATABASE_URL: mysql://root@localhost:3306/flightcontrol_test

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=16384"
      DATOCMS_API_TOKEN: ${{ secrets.DATOCMS_API_TOKEN }}
      DATOCMS_READONLY_API_TOKEN: b473cda74c68c3010b3fc72eca11b8
      FC_GIT_PR_NUMBER: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - run: sh vercel.sh