name: CI

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DATABASE_URL: mysql://root@localhost:3306/flightcontrol_test

jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: "--max_old_space_size=16384"
      FULL_ACCESS: ${{ secrets.FULL_ACCESS }}
      GIT_PR_REF: ${{ github.event.pull_request.number }}
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - run: ./vercel.sh